import type { Metadata } from "next"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter"
import { Inter } from "next/font/google"
import "./globals.css"
import { getServerSession } from "next-auth"
import SessionProvider from "./components/SessionProvider"
import { ReactQueryClientProvider } from "./components/ReactQueryClientProvider"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import NavMenu from "./components/NavMenu"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
}

//---------------------------------------------------------

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen bg-theme-lightPeach`}
      >
        <AppRouterCacheProvider>
          <SessionProvider session={session}>
            <ReactQueryClientProvider>
              <ReactQueryDevtools buttonPosition="bottom-left" />
              {session && <NavMenu />}
              {children}
            </ReactQueryClientProvider>
          </SessionProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

export default RootLayout
